name: Build and Package

on: [push]

jobs:
  
  # Build artifacts
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # We need msbuild and NuGet
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1
      
      - name: Restore NuGet Packages
        run: nuget restore PowerPointToOSC.sln

      # Build artifacts
      - name: Build
        run:  msbuild PowerPointToOSC.sln /p:RuntimeIdentifier=win-x64 /p:Configuration=Release
      
      # Download sendosc.exe
      - name: Download sendosc
        run: |
          Invoke-WebRequest https://github.com/yoggy/sendosc/releases/download/v1.0.2/sendosc-win-1.0.2.zip -OutFile sendosc.zip
          7z -y e sendosc.zip -o.\bin\Release\net48\win-x64

      # Upload artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: PowerPointToOSC
          path: bin\Release\net48\win-x64
          retention-days: 7

      - name: Generate zip bundle
        run: 7z a -tzip PowerPointToOSC.zip .\bin\Release\net48\win-x64\*
      
      - if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        name: Publish latest pre-release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          files: |
            PowerPointToOSC.zip

      - if: startsWith(github.ref, 'refs/tags/v')
        name: Publish tagged release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            PowerPointToOSC.zip