name: Build and Package

on: [push, workflow_dispatch]

jobs:
  
  # Build artifacts
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # We need msbuild and NuGet
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1
      
      - name: Restore NuGet Packages
        run: nuget restore PowerPointToOSC.sln

      # Build artifacts
      - name: Build
        run:  msbuild PowerPointToOSC.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile

      # Upload artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Dist
          path: bin\Release\Publish
